# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Heap-Simple-XS
version:      0.10
version_from: lib/Heap/Simple/XS/Package.pm
installdirs:  site
requires:
    Heap::Simple:                  0.09
    Test::More:                    0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
